package com.patrickchang.atomrebuild.common.world.item;

import com.patrickchang.atomrebuild.AtomRebuild;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(AtomRebuild.MOD_ID)
public class ModItems {
    public static final Item ATOM_REBUILDER_BLOCK = null;
    public static final Item TEST_SUBSTANCE = null;
    public static final Item HYDROGEN = null;
    public static final Item HELIUM = null;
    public static final Item LITHIUM = null;
    public static final Item BERYLLIUM = null;
    public static final Item BORON = null;
    public static final Item CARBON = null;
    public static final Item NITROGEN = null;
    public static final Item OXYGEN = null;
    public static final Item FLUORINE = null;
    public static final Item NEON = null;
    public static final Item SODIUM = null;
    public static final Item MAGNESIUM = null;
    public static final Item ALUMINUM = null;
    public static final Item SILICON = null;
    public static final Item PHOSPHORUS = null;
    public static final Item SULFUR = null;
    public static final Item CHLORINE = null;
    public static final Item ARGON = null;
    public static final Item POTASSIUM = null;
    public static final Item CALCIUM = null;
    public static final Item SCANDIUM = null;
    public static final Item TITANIUM = null;
    public static final Item VANADIUM = null;
    public static final Item CHROMIUM = null;
    public static final Item MANGANESE = null;
    public static final Item IRON = null;
    public static final Item COBALT = null;
    public static final Item NICKEL = null;
    public static final Item COPPER = null;
    public static final Item ZINC = null;
    public static final Item GALLIUM = null;
    public static final Item GERMANIUM = null;
    public static final Item ARSENIC = null;
    public static final Item SELENIUM = null;
    public static final Item BROMINE = null;
    public static final Item KRYPTON = null;
    public static final Item RUBIDIUM = null;
    public static final Item STRONTIUM = null;
    public static final Item YTTRIUM = null;
    public static final Item ZIRCONIUM = null;
    public static final Item NIOBIUM = null;
    public static final Item MOLYBDENUM = null;
    public static final Item TECHNETIUM = null;
    public static final Item RUTHENIUM = null;
    public static final Item RHODIUM = null;
    public static final Item PALLADIUM = null;
    public static final Item SILVER = null;
    public static final Item CADMIUM = null;
    public static final Item INDIUM = null;
    public static final Item TIN = null;
    public static final Item ANTIMONY = null;
    public static final Item TELLURIUM = null;
    public static final Item IODINE = null;
    public static final Item XENON = null;
}
